### ISSUE TITLE
Tiktok AI Voice

### ISSUE THREAD

**Issue by jiweiyeah** [aidevtoolkit/indie-hacker-tools#1]
工具：https://tiktokaivoice.top
简介：
● 免费使用 AI 接口将文本转换成在 tiktok 中流行的语音
● 可以选择多种不同的音色重复生成并下载为 mp3 格式
● 生成速度飞快，音质机械感极低
● 支持多语言版本
● 支持 github 和 google 登录
● 适配 pc 端和 移动端

<img width="1367" alt="image" src="https://github.com/aidevtoolkit/indie-hacker-tools/assets/156828820/3c6ac1d3-c487-48ec-9ca7-a58d53046897">
<img width="1194" alt="image" src="https://github.com/aidevtoolkit/indie-hacker-tools/assets/156828820/3e6b2803-c1d9-4c3d-851c-02b4c5708ff8">
<img width="1156" alt="image" src="https://github.com/aidevtoolkit/indie-hacker-tools/assets/156828820/b2459a38-c9f1-47da-a8c4-fece5672182a">
<img width="991" alt="image" src="https://github.com/aidevtoolkit/indie-hacker-tools/assets/156828820/6dc1409e-1e7c-4111-8c09-f71857e8daba">
<img width="480" alt="image" src="https://github.com/aidevtoolkit/indie-hacker-tools/assets/156828820/673cac80-4a82-40b1-8bf7-08a71a71be8d">

**Comment by luobogor** [comment]
与独立开发者主题不符
