### ISSUE TITLE
【工具自荐】一款酷炫的背景图生成工具 ✔️极致 ✔️免费 ✔️开源

### ISSUE THREAD

**Issue by winterx** [aidevtoolkit/indie-hacker-tools#3]
# Color4Bg

### 🎯 产品简介：

各位独立开发者、创作者、极客大神们

如果你们辛苦制作的网站、工具、落地页、PPT等项目，不知道该使用什么样的背景图，但是希望拥有一个像 Stripe、Replicate 那样的酷炫的动态背景，那么**你一定要试试 Color4Bg 这款工具！**

Color4bg可以在线生成各种颜色主题的酷炫背景图片，适合于用在各类网页、站点、演示文稿项目中。免费，极速，支持通过JS的方式引入。

在线体验&使用地址：https://www.color4bg.com/

![meta-og-image-zh](https://github.com/user-attachments/assets/aea0c1bd-3829-401d-b06f-ba210eda7800)

### 🚀 功能介绍：
- 多种彩色背景生成器可选，从流体类型到随机渐变
- 所有的背景生成器均可以自定义颜色
- 要是你懒得手动调颜色，工具自带有多个色系的上百种色彩搭配，直接切换，每个都很好看
- 支持导出为 PNG 、或 Webm 视频
- 支持将背景通过 JS 脚本引入你的网页项目（JS文件 size < 100k）
- 多语言支持

### 📕 使用说明
1. 首先，在首页「抽象艺术背景」栏目中，选择你中意的背景模板
2. 点击进入任意一款背景生成器中，你都可以：手动调节每一个颜色、切换颜色主题、随机换一个主题
3. 也可以改变一些样式参数，比如用随机seed试试
4. 然后，点击 `下载` 即可将这个背景保存为PNG图片或Webm视频

### 🎬 功能演示

https://github.com/user-attachments/assets/91480114-05fe-4e60-a705-80b0c8e0e393

### ⌨️ 一些快捷键：
- `Esc` 可以隐藏所有UI，这样就可以将这个页面当做一个纯背景使用，或者通过 <iframe> 使用
- `空格` 可以暂停/播放

### 🛠 通过JS方式引入前端项目
你可以下载当前这个背景的JS文件，并且根据只是弹框中的方式调用即可

https://github.com/user-attachments/assets/7656b1dd-7b62-4ccf-9e9c-146c0038282b

### 📦 开源
该项目基于 OGL 开发，开源地址：
https://github.com/winterx/color4bg.js

**Comment by luobogor** [comment]
@winterx 审核通过，看是否需要补充文案。

**Comment by winterx** [comment]
> @winterx 审核通过，看是否需要补充文案。

@luobogor 非常感谢！我补充了一些文案和介绍视频上去

**Comment by luobogor** [comment]
@winterx 视频有 youtube 或其他地址链接吗，网站还没有开发视频功能，只能嵌 iframe 播放。

**Comment by luobogor** [comment]
@winterx 下周帮你推
