### ISSUE TITLE
您的工具箱给了我一些思路

### ISSUE THREAD

**Issue by Gorvey** [aidevtoolkit/indie-hacker-tools#4]
我最近部署了一个前端导航站，[https://jscool.cn](https://jscool.cn)，这些都是我平时收集的资源，发布成网页是为了更好的回顾与分享。
但是功能很少，我也不知道怎么加，直到看到了您的工具箱。我有了些新的想法
1. 我现在的分类太乱了，我打算按照 前端从0基础入门到实战，然后简历刷题，进入公司做项目，最后提升自己这样去分类
2. 给每个网站都加上详细的介绍
3. 合并同类网站，只展示最优质的几个，在这个网站右上角加一个计数器，点击显示所有的同类网站。这样能很好的控制资源数量和质量

**Comment by luobogor** [comment]
1. 离钱近的话题是很有吸引力的。第一点问题不大，可以再清晰一点，你的主题导向可以是怎样跳槽到好的大厂，或者怎样找到有潜力的小公司（比如一些AI创业公司），或者怎样规划升职加薪都OK。
2. 可以搞个博客模块，写一些前端开发相关的文章。
3. 教程模块可以贴一些实用的掘金小册子，小册子销出有分佣赚点零花钱。

@Gorvey
